server:
  port: 8080
  tomcat:
    accesslog:
      buffered: true
      directory: /logs
      enabled: true
      encoding: UTF-8
      pattern: combined
      prefix: ${spring.application.name}-access
      rename-on-rotate: true
      request-attributes-enabled: false
      suffix: .log

spring:
  application:
    name: foundation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 2117826525
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.0.2:3306/simulation?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: mysql
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    view-names: html/*
  web:
    resources:
      static-locations: classpath:/static/

foundation:
  transaction:
    isolation: ISOLATION_READ_COMMITTED
    propagation: PROPAGATION_REQUIRED

mybatis:
  config-location: classpath:/config/mybatis/mybatis-config.xml
  mapper-locations: classpath:config/mybatis/mapper/*.xml
  type-aliases-package: com.foundation.core.entity